import { expect, it } from 'vitest';
import { createWorkspace, parseWorkspace } from '../src/storage';
import type { ComponentDefinition } from '../src/contracts';
import { encapsulateSelection } from '../src/components';
import { referenceCircuit } from './fixtures';

function identity(id: string, dependency?: string): ComponentDefinition {
  return { id, version: 1, name: id, inputs: [{ id: 'A', label: 'A', bits: 1 }],
    outputs: [{ id: 'Y', label: 'Y', bits: 1 }], dependencies: dependency ? [dependency] : [], sourceLevel: 1,
    graph: { nodes: [
      { id: 'A', type: 'INPUT', label: 'A', bits: 1, position: { x: 0, y: 0 } },
      ...(dependency ? [{ id: 'nested', type: 'COMPONENT' as const, label: 'nested', componentKey: dependency,
        position: { x: 100, y: 0 } }] : []),
      { id: 'Y', type: 'OUTPUT', label: 'Y', bits: 1, position: { x: 200, y: 0 } },
    ], wires: dependency ? [
      { id: 'w-a', source: 'A', sourceHandle: 'out', target: 'nested', targetHandle: 'A' },
      { id: 'w-y', source: 'nested', sourceHandle: 'Y', target: 'Y', targetHandle: 'in' },
    ] : [{ id: 'w-y', source: 'A', sourceHandle: 'out', target: 'Y', targetHandle: 'in' }] } };
}

it('round-trips nested definitions and retains older immutable versions', () => {
  const state = createWorkspace();
  const leaf = identity('leaf');
  state.library = { ...state.library, 'leaf@1': leaf, 'leaf@2': { ...structuredClone(leaf), version: 2, name: 'leaf revised' },
    'outer@1': identity('outer', 'leaf@1') };
  state.circuits[2].nodes.push({ id: 'instance', type: 'COMPONENT', label: 'outer', componentKey: 'outer@1',
    position: { x: 300, y: 100 } });
  state.circuits[2].wires.push(
    { id: 'w-instance-in', source: 'A', sourceHandle: 'out', target: 'instance', targetHandle: 'A' },
    { id: 'w-instance-out', source: 'instance', sourceHandle: 'Y', target: 'Y', targetHandle: 'in' });
  const restored = parseWorkspace(JSON.stringify(state));
  expect(restored.library).toEqual(state.library);
  expect(restored.circuits[2]).toEqual(state.circuits[2]);
  expect(restored.library['outer@1'].dependencies).toEqual(['leaf@1']);
});

it('rejects missing dependencies in unused library definitions', () => {
  const state = createWorkspace();
  state.library = { ...state.library, 'outer@1': identity('outer', 'missing@1') };
  expect(() => parseWorkspace(JSON.stringify(state))).toThrow();
});

it('rejects recursive component dependencies', () => {
  const state = createWorkspace();
  state.library = { ...state.library, 'a@1': identity('a', 'b@1'), 'b@1': identity('b', 'a@1') };
  expect(() => parseWorkspace(JSON.stringify(state))).toThrow();
});

it('rejects invalid bus inputs and malformed component widths', () => {
  const state = createWorkspace();
  state.inputs[12].A = 16;
  expect(() => parseWorkspace(JSON.stringify(state))).toThrow(/输入/);
  state.inputs[12].A = 0;
  state.library = { ...state.library, 'leaf@1': identity('leaf') };
  state.library['leaf@1'].inputs[0].bits = 3;
  expect(() => parseWorkspace(JSON.stringify(state))).toThrow();
});

it('accepts nested definitions generated by actual selection encapsulation', () => {
  const state = createWorkspace();
  const circuit = referenceCircuit(15);
  const first = encapsulateSelection(circuit, circuit.nodes.filter(n => n.type !== 'INPUT' && n.type !== 'OUTPUT').map(n => n.id), '半加器内部');
  const second = encapsulateSelection(first.circuit, first.circuit.nodes.filter(n => n.type === 'COMPONENT').map(n => n.id), '嵌套半加器', first.library);
  state.circuits[15] = second.circuit;
  state.library = { ...state.library, ...second.library };
  expect(parseWorkspace(JSON.stringify(state)).library).toEqual(state.library);
});
